# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('puzzles', '0002_puzzle_times_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='rated_by',
            field=models.ManyToManyField(related_name='puzzles_rated', to='login.User'),
        ),
    ]
