# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_puzzle_rated_by'),
        ('puzzles', '0004_puzzle_times_rated'),
    ]

    operations = [
    ]
